# Generated by Django 3.2.5 on 2021-07-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yamdbuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='yamdbuser',
            name='code',
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='password',
            field=models.CharField(max_length=70, verbose_name='Пароль пользователя'),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
