# Generated by Django 3.2.5 on 2021-07-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210714_2100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YamdbUser',
            new_name='FoodUser',
        ),
    ]
